-- ===== بيانات الأبطال (مولَّدة تلقائياً من index.html) =====
insert into heroes (slug, ar, role, lane, tier, img, pop, overview, notes, combos, skill_order, build) values
('esmeralda', 'إزميرالدا', 'fighter', 'خط الخبرة', 'S+', null, 92, 'مقاتلة تحوّل ضرر الأعداء إلى درع أزرق ثم تحرّره كضرر سحري. عادت في باتش 2.1.90 إلى أسلوب البقاء الطويل، وصار إسقاطها في المبارزة الفردية شبه مستحيل.', '{"strength":["تحوّل جزءاً من الضرر الوارد إلى درع يعزز هجومها","مبارزة فردية قوية جداً بعد الآيتم الثاني","تصعد بقوة في منتصف ونهاية اللعبة"],"weakness":["بطيئة في اللحظات الأولى من الاشتباك","الضرر المئوي يتجاوز درعها بالكامل","ضعيفة قبل المستوى ٤"],"pick_when":["حين يملك الخصم فريقاً يعتمد على الضرر التقليدي المستمر"],"avoid_when":["حين يملك الخصم أكثر من مصدر ضرر حقيقي (كاري، كلود)"]}'::jsonb, '[{"kind":"pro","title":"كومبو المحترفين","steps":["S2","S1","أساسي","ULT"],"notes":"ادخلي بالثانية، ثبّتي بالأولى، فعّلي الألت بعد تكديس الدرع"}]'::jsonb, '{"priority":["S2","S1","ULT"],"notes":"ركّزي المهارة الأولى مبكراً للضغط، وارفعي الألت في كل فرصة.","map":{"1":"S1","2":"S2","3":"S1","4":"ULT","5":"S1","6":"ULT","7":"S1","8":"S2","9":"S2","10":"ULT","11":"S2","12":"S2","13":"S2","14":"S2","15":"ULT"}}'::jsonb, '{"summary":"بيلد بقاء يستغل تحويل الدروع، مع قطع تحكّم مبكر يحمي دورتها الأولى.","items":[{"n":"حذاء المقاتل","p":710,"r":"مقاومة تحكّم مبكرة"},{"n":"عصا التاريخ الغامض","p":2250,"r":"يحوّل دمها لقوة سحرية"},{"n":"درع الجليد الخالد","p":2150,"r":"يبطئ رماة الخصم"},{"n":"وشاح أورانوس","p":2120,"r":"ضد الضرر السحري"},{"n":"خوذة الخلود","p":2050,"r":"تعافٍ مستمر"},{"n":"عباءة أثينا","p":2250,"r":"ضد الانفجار السحري"}],"emblem":"شارة المقاتل","spell":"الإعدام","alt":"الوميض"}'::jsonb),
('khufra', 'خفرة', 'tank', 'التجوال', 'S', null, 87, 'دبابة تحكّم — كرته الرملية تُلغي كل حالات الاندفاع، ما يجعله الردّ المباشر على فرق الحركة العالية مثل فاني ولينغ.', '{"strength":["يُلغي كل الاندفاعات بمهارته الثانية","دفاع مرتفع منذ بداية اللعبة","بدء اشتباك موثوق للفريق"],"weakness":["حركته الأساسية بطيئة","ضرره منخفض بلا آيتمات هجومية"],"pick_when":["حين يملك الخصم بطلاً يعتمد على الاندفاع"],"avoid_when":["حين يملك فريقك بالفعل دبابة تحكّم قوية"]}'::jsonb, '[{"kind":"team_fight","title":"فتح الاشتباك","steps":["S1","S2","ULT","أساسي"],"notes":"ادخل أولاً، جمّد الأهداف، ثم فعّل الألت"}]'::jsonb, '{"priority":["S2","S1","ULT"],"notes":"ارفع الكرة الرملية أولاً — أداتك الأهم في كل مرحلة.","map":{"1":"S2","2":"S1","3":"S2","4":"ULT","5":"S2","6":"ULT","7":"S2","8":"S1","9":"S1","10":"ULT","11":"S1","12":"S1","13":"S1","14":"S1","15":"ULT"}}'::jsonb, '{"summary":"بيلد دفاعي كامل يركّز على البقاء وفتح الاشتباك بأمان.","items":[{"n":"حذاء النقانق الغامضة","p":750,"r":"حركة إضافية"},{"n":"درع الصلابة","p":1000,"r":"دفاع مبكر"},{"n":"درع الجليد الخالد","p":2150,"r":"يبطئ رماة الخصم"},{"n":"خوذة الشيطان","p":2050,"r":"استعادة درع مستمرة"},{"n":"وشاح أورانوس","p":2120,"r":"ضد الضرر السحري"},{"n":"الدرع الإلهي","p":2030,"r":"يحمي من العزل"}],"emblem":"شارة الدبابة","spell":"العقاب","alt":"الوميض"}'::jsonb),
('melissa', 'ميليسا', 'mm', 'خط الذهب', 'S', null, 86, 'رامية تستخدم دميتها للدفاع عن نفسها وتتنقّل عبر مظلة مقاومة للتحكّم. قُوِّيت في باتش 2.1.90.', '{"strength":["مظلتها تمنحها هروباً مقاوماً للتحكّم","دميتها تحميها من الاقتراب المباشر"],"weakness":["بطيئة الحركة بلا مهارات مفعّلة","ضعيفة جداً في الدقائق الأولى"],"pick_when":["حين تحتاجين راميةً تصمد أمام القتلة قليلاً أكثر من المعتاد"]}'::jsonb, '[{"kind":"beginner","title":"كومبو أساسي","steps":["S1","أساسي","S2"],"notes":"ثبّتي الهدف بالدمية ثم اضربي من الأمان"}]'::jsonb, '{"priority":["S1","S2","ULT"],"notes":"ارفعي الأولى أولاً لتثبيت الدمية مبكراً.","map":{"1":"S1","2":"S2","3":"S1","4":"ULT","5":"S1","6":"ULT","7":"S1","8":"S1","9":"S2","10":"ULT","11":"S2","12":"S2","13":"S2","14":"S2","15":"ULT"}}'::jsonb, '{"summary":"بيلد DPS مع عنصر ضرر حقيقي واحد ضد الدبابات.","items":[{"n":"حذاء السرعة القاتلة","p":600,"r":"سرعة هجوم أساسية"},{"n":"فأس الجزار الجائع","p":2150,"r":"ضرر حقيقي ضد الدبابات"},{"n":"مطرقة الرعد الملتهبة","p":2180,"r":"انفجار كل ٦ ضربات"},{"n":"عين الصياد الشرسة","p":2060,"r":"مدى إضافي"}],"emblem":"شارة الرامي","spell":"الإعدام","alt":"التطهير"}'::jsonb),
('hayabusa', 'هاياباسا', 'assassin', 'الأدغال', 'S', null, 84, 'قاتل ظلال يتنقّل عبر الشادو، ويصبح غير قابل للاستهداف أثناء ألته.', '{"strength":["يهرب ويعيد التموضع عبر ظلاله الثلاثة","ألته غير قابلة للاستهداف"],"weakness":["يعتمد كلياً على الكومبو الكامل","التحكّم الفوري قبل الظلال يُلغي تهديده"],"pick_when":["حين تحتاج جانغلر يفرض ضغطاً سريعاً على الخريطة"]}'::jsonb, '[{"kind":"one_v_one","title":"مبارزة فردية","steps":["S1","ULT","أساسي"],"notes":"ثبّت الهدف بالشوريكن قبل الألت مباشرة"}]'::jsonb, '{"priority":["S1","S2","ULT"],"notes":"المهارة الأولى تحمل أعلى ضرر أساسي — ركّزها أولاً.","map":{"1":"S1","2":"S2","3":"S1","4":"ULT","5":"S1","6":"ULT","7":"S1","8":"S1","9":"S2","10":"ULT","11":"S2","12":"S2","13":"S2","14":"S2","15":"ULT"}}'::jsonb, '{"summary":"بيلد ضرر انفجاري مع تخفيض كولداون لتكرار الكومبو بسرعة.","items":[{"n":"فأس الحرب","p":1990,"r":"ضرر انفجاري أساسي"},{"n":"حذاء الانتقام السريع","p":2180,"r":"يقلل كولداون مهاراته"},{"n":"شفرة الملازم","p":1980,"r":"تكديس ضرر على الهدف"},{"n":"درع الغزو","p":2000,"r":"يخترق دفاع الدبابات"}],"emblem":"شارة القاتل","spell":"الإعدام","alt":"الوميض"}'::jsonb),
('estes', 'إستس', 'sup', 'التجوال', 'B', null, 85, 'أقوى معالج في اللعبة — علاجه المستمر يبقي الفريق حياً في الاشتباكات الطويلة، ما لم يُقطع.', '{"strength":["أعلى كمّية علاج بين كل المساندين","علاج مساحي يشمل الفريق بأكمله"],"weakness":["بلا أي أداة هجومية","عديم الفائدة إن قُطِع علاجه"],"avoid_when":["حين يملك الخصم أكثر من مصدر لقطع العلاج (باكسيا، ديروث)"]}'::jsonb, '[{"kind":"team_fight","title":"دعم الاشتباك","steps":["ULT","S1","S2"],"notes":"فعّل الألت على أضعف حليف فور بدء الاشتباك"}]'::jsonb, '{"priority":["S1","S2","ULT"],"notes":"المهارة الأولى (العلاج المساحي) أولوية من المستوى الأول.","map":{"1":"S1","2":"S2","3":"S1","4":"ULT","5":"S1","6":"ULT","7":"S1","8":"S1","9":"S2","10":"ULT","11":"S2","12":"S2","13":"S2","14":"S2","15":"ULT"}}'::jsonb, '{"summary":"بيلد مانا وكولداون صرف يخدم دورة العلاج المستمرة.","items":[{"n":"حذاء الطاقة السحرية","p":730,"r":"مانا إضافية"},{"n":"تعويذة المحيط","p":1030,"r":"استعادة بعد المهارات"},{"n":"ساعة الروح الرملية","p":2150,"r":"علاج أكثر تكراراً"},{"n":"خوذة الملاك الحارس","p":1980,"r":"درع طارئ لأضعف حليف"}],"emblem":"شارة المساند","spell":"العدو","alt":"التطهير"}'::jsonb),
('zhuxin', 'تشوشين', 'mage', 'الخط الأوسط', 'B', null, 58, 'ساحرة تسحب الأعداء بسلاسل الظل قبل قصفهم بضرر منطقة واسع. خُفِّض مدى مهارتها الثانية في 2.1.90.', '{"strength":["تحكّم جماعي واسع","ضرر منطقة مرتفع في الاشتباك الجماعي"],"weakness":["بطيئة الحركة وعرضة للقتلة","خُفِّض مداها الأخير مؤخراً"]}'::jsonb, '[{"kind":"team_fight","title":"فتح الاشتباك","steps":["S2","ULT","S1"],"notes":"اسحبي أكبر عدد ممكن قبل تفعيل الألت"}]'::jsonb, null, null),
('miya', 'مايا', 'mm', 'خط الذهب', 'C', null, 92, null, null, null, null, null),
('bruno', 'برونو', 'mm', 'خط الذهب', null, null, 74, null, null, null, null, null),
('clint', 'كلينت', 'mm', 'خط الذهب', null, null, 34, null, null, null, null, null),
('moskov', 'موسكوف', 'mm', 'خط الذهب', null, null, 75, null, null, null, null, null),
('irithel', 'إيريثيل', 'mm', 'خط الذهب', null, null, 60, null, null, null, null, null),
('lesley', 'ليزلي', 'mm', 'خط الذهب', null, null, 62, null, null, null, null, null),
('granger', 'غرانجر', 'mm', 'خط الذهب', 'A', null, 83, null, null, null, null, null),
('wanwan', 'وان وان', 'mm', 'خط الذهب', 'A', null, 78, null, null, null, null, null),
('claude', 'كلود', 'mm', 'خط الذهب', 'A', null, 85, null, null, null, null, null),
('kimmy', 'كيمي', 'mm', 'خط الذهب', null, null, 61, null, null, null, null, null),
('beatrix', 'بياتريكس', 'mm', 'خط الذهب', 'S', null, 76, null, null, null, null, null),
('brody', 'برودي', 'mm', 'خط الذهب', null, null, 66, null, null, null, null, null),
('ixia', 'إكسيا', 'mm', 'خط الذهب', null, null, 65, null, null, null, null, null),
('hanabi', 'هانابي', 'mm', 'خط الذهب', 'A', null, 97, null, null, null, null, null),
('yisunshin', 'يي سون شين', 'mm', 'خط الذهب', null, null, 50, null, null, null, null, null),
('popolandkupa', 'بوبول وكوبا', 'mm', 'خط الذهب', null, null, 52, null, null, null, null, null),
('eudora', 'يودورا', 'mage', 'الخط الأوسط', 'B', null, 83, null, null, null, null, null),
('gord', 'غورد', 'mage', 'الخط الأوسط', 'A', null, 60, null, null, null, null, null),
('alice', 'أليس', 'mage', 'الخط الأوسط', null, null, 34, null, null, null, null, null),
('nana', 'نانا', 'mage', 'الخط الأوسط', 'B', null, 80, null, null, null, null, null),
('cyclops', 'سايكلوبس', 'mage', 'الخط الأوسط', null, null, 47, null, null, null, null, null),
('kagura', 'كاغورا', 'mage', 'الخط الأوسط', 'A', null, 84, null, null, null, null, null),
('aurora', 'أورورا', 'mage', 'الخط الأوسط', null, null, 34, null, null, null, null, null),
('vexana', 'فيكسانا', 'mage', 'الخط الأوسط', 'B', null, 70, null, null, null, null, null),
('odette', 'أوديت', 'mage', 'الخط الأوسط', null, null, 51, null, null, null, null, null),
('pharsa', 'فارسا', 'mage', 'الخط الأوسط', null, null, 34, null, null, null, null, null),
('change', 'تشانغ آه', 'mage', 'الخط الأوسط', null, null, 53, null, null, null, null, null),
('lunox', 'لونوكس', 'mage', 'الخط الأوسط', 'A', null, 79, null, null, null, null, null),
('harley', 'هارلي', 'mage', 'الأدغال', null, null, 34, null, null, null, null, null),
('vale', 'فيل', 'mage', 'الخط الأوسط', null, null, 52, null, null, null, null, null),
('lylia', 'ليليا', 'mage', 'الخط الأوسط', null, null, 51, null, null, null, null, null),
('cecilion', 'سيسيليون', 'mage', 'الخط الأوسط', null, null, 72, null, null, null, null, null),
('yve', 'إيف', 'mage', 'الخط الأوسط', null, null, 54, null, null, null, null, null),
('valentina', 'فالنتينا', 'mage', 'الخط الأوسط', 'S', null, 77, null, null, null, null, null),
('xavier', 'زافير', 'mage', 'الخط الأوسط', null, null, 57, null, null, null, null, null),
('novaria', 'نوفاريا', 'mage', 'الخط الأوسط', null, null, 48, null, null, null, null, null),
('luoyi', 'لوه يي', 'mage', 'الخط الأوسط', null, null, 50, null, null, null, null, null),
('valir', 'فالير', 'mage', 'الخط الأوسط', null, null, 49, null, null, null, null, null),
('kadita', 'كاديتا', 'mage', 'الخط الأوسط', null, null, 52, null, null, null, null, null),
('zhask', 'زاسك', 'mage', 'الخط الأوسط', null, null, 46, null, null, null, null, null),
('harith', 'هاريث', 'mage', 'الخط الأوسط', 'A', null, 82, null, null, null, null, null),
('zetian', 'زيتيان', 'mage', 'الخط الأوسط', 'S', null, 75, null, null, null, null, null),
('saber', 'سيبر', 'assassin', 'الأدغال', 'B', null, 76, null, null, null, null, null),
('fanny', 'فاني', 'assassin', 'الأدغال', 'B', null, 80, null, null, null, null, null),
('natalia', 'ناتاليا', 'assassin', 'الأدغال', null, null, 70, null, null, null, null, null),
('lancelot', 'لانسلوت', 'assassin', 'الأدغال', 'S', null, 88, null, null, null, null, null),
('helcurt', 'هيلكيرت', 'assassin', 'الأدغال', 'B', null, 74, null, null, null, null, null),
('gusion', 'غوسيون', 'assassin', 'الأدغال', 'A', null, 89, null, null, null, null, null),
('karina', 'كارينا', 'assassin', 'الأدغال', 'B', null, 77, null, null, null, null, null),
('selena', 'سيلينا', 'assassin', 'الأدغال', 'B', null, 78, null, null, null, null, null),
('ling', 'لينغ', 'assassin', 'الأدغال', 'A', null, 83, null, null, null, null, null),
('aamon', 'آمون', 'assassin', 'الأدغال', null, null, 74, null, null, null, null, null),
('benedetta', 'بينيديتا', 'assassin', 'الأدغال', null, null, 77, null, null, null, null, null),
('yin', 'يين', 'assassin', 'الأدغال', null, null, 58, null, null, null, null, null),
('joy', 'جوي', 'assassin', 'الأدغال', null, null, 53, null, null, null, null, null),
('nolan', 'نولان', 'assassin', 'الأدغال', 'A', null, 79, null, null, null, null, null),
('hanzo', 'هانزو', 'assassin', 'الأدغال', null, null, 55, null, null, null, null, null),
('julian', 'جوليان', 'assassin', 'الأدغال', 'A', null, 76, null, null, null, null, null),
('suyou', 'سويو', 'assassin', 'الأدغال', null, null, 47, null, null, null, null, null),
('hirara', 'هيرارا', 'assassin', 'الأدغال', null, null, 45, null, null, null, null, null),
('balmond', 'بالموند', 'fighter', 'خط الخبرة', 'C', null, 55, null, null, null, null, null),
('alucard', 'ألوكارد', 'fighter', 'خط الخبرة', null, null, 88, null, null, null, null, null),
('zilong', 'زيلونغ', 'fighter', 'خط الخبرة', null, null, 87, null, null, null, null, null),
('freya', 'فريا', 'fighter', 'خط الخبرة', 'B', null, 75, null, null, null, null, null),
('argus', 'أرغوس', 'fighter', 'خط الخبرة', 'C', null, 58, null, null, null, null, null),
('alpha', 'ألفا', 'fighter', 'خط الخبرة', null, null, 59, null, null, null, null, null),
('ruby', 'روبي', 'fighter', 'خط الخبرة', null, null, 63, null, null, null, null, null),
('bane', 'بين', 'fighter', 'خط الخبرة', 'C', null, 52, null, null, null, null, null),
('sun', 'صن', 'fighter', 'الأدغال', null, null, 34, null, null, null, null, null),
('chou', 'تشو', 'fighter', 'خط الخبرة', 'A', null, 90, null, null, null, null, null),
('lapulapu', 'لابو لابو', 'fighter', 'خط الخبرة', null, null, 34, null, null, null, null, null),
('jawhead', 'جوهيد', 'fighter', 'خط الخبرة', null, null, 56, null, null, null, null, null),
('martis', 'مارتيس', 'fighter', 'خط الخبرة', null, null, 57, null, null, null, null, null),
('aldous', 'ألدوس', 'fighter', 'خط الخبرة', null, null, 48, null, null, null, null, null),
('leomord', 'ليومورد', 'fighter', 'خط الخبرة', null, null, 49, null, null, null, null, null),
('thamuz', 'ثاموز', 'fighter', 'خط الخبرة', null, null, 52, null, null, null, null, null),
('minsitthar', 'مينستار', 'fighter', 'التجوال', 'A', null, 66, null, null, null, null, null),
('kaja', 'كاجا', 'fighter', 'التجوال', null, null, 57, null, null, null, null, null),
('xborg', 'إكس بورغ', 'fighter', 'خط الخبرة', 'B', null, 69, null, null, null, null, null),
('terizla', 'تيريزلا', 'fighter', 'خط الخبرة', 'B', null, 70, null, null, null, null, null),
('dyrroth', 'ديروث', 'fighter', 'خط الخبرة', 'A', null, 78, null, null, null, null, null),
('silvanna', 'سيلفانا', 'fighter', 'خط الخبرة', 'B', null, 67, null, null, null, null, null),
('yuzhong', 'يو تشونغ', 'fighter', 'خط الخبرة', 'B', null, 73, null, null, null, null, null),
('khaleed', 'خالد', 'fighter', 'خط الخبرة', null, null, 56, null, null, null, null, null),
('barats', 'باراتس', 'tank', 'خط الخبرة', null, null, 46, null, null, null, null, null),
('paquito', 'باكيتو', 'fighter', 'خط الخبرة', 'A', null, 80, null, null, null, null, null),
('phoveus', 'فوفيوس', 'fighter', 'خط الخبرة', 'S', null, 78, null, null, null, null, null),
('aulus', 'أولوس', 'fighter', 'خط الخبرة', 'A', null, 80, null, null, null, null, null),
('fredrinn', 'فردرن', 'tank', 'الأدغال', 'A', null, 73, null, null, null, null, null),
('arlott', 'أرلوت', 'fighter', 'خط الخبرة', null, null, 53, null, null, null, null, null),
('cici', 'سيسي', 'fighter', 'خط الخبرة', null, null, 50, null, null, null, null, null),
('guinevere', 'غوينيفير', 'fighter', 'خط الخبرة', 'A', null, 75, null, null, null, null, null),
('masha', 'ماشا', 'fighter', 'الأدغال', 'A', null, 81, null, null, null, null, null),
('hilda', 'هيلدا', 'fighter', 'خط الخبرة', null, null, 60, null, null, null, null, null),
('roger', 'روجر', 'fighter', 'خط الخبرة', 'B', null, 66, null, null, null, null, null),
('badang', 'بادانغ', 'fighter', 'خط الخبرة', 'B', null, 68, null, null, null, null, null),
('lukas', 'لوكاس', 'fighter', 'خط الخبرة', null, null, 50, null, null, null, null, null),
('sora', 'سورا', 'fighter', 'الأدغال', 'S+', null, 88, null, null, null, null, null),
('uranus', 'أورانوس', 'tank', 'خط الخبرة', null, null, 44, null, null, null, null, null),
('marcel', 'مارسيل', 'fighter', 'خط الخبرة', null, null, 56, null, null, null, null, null),
('obsidia', 'أوبسيديا', 'mm', 'خط الذهب', null, null, 60, null, null, null, null, null),
('tigreal', 'تيغريل', 'tank', 'التجوال', 'B', null, 89, null, null, null, null, null),
('akai', 'أكاي', 'tank', 'الأدغال', 'B', null, 76, null, null, null, null, null),
('franco', 'فرانكو', 'tank', 'التجوال', 'B', null, 90, null, null, null, null, null),
('minotaur', 'مينوتور', 'tank', 'التجوال', null, null, 55, null, null, null, null, null),
('lolita', 'لوليتا', 'tank', 'التجوال', null, null, 57, null, null, null, null, null),
('grock', 'غروك', 'tank', 'التجوال', null, null, 56, null, null, null, null, null),
('hylos', 'هيلوس', 'tank', 'التجوال', null, null, 47, null, null, null, null, null),
('johnson', 'جونسون', 'tank', 'التجوال', null, null, 58, null, null, null, null, null),
('baxia', 'باكسيا', 'tank', 'الأدغال', 'B', null, 68, null, null, null, null, null),
('atlas', 'أطلس', 'tank', 'التجوال', 'A', null, 82, null, null, null, null, null),
('belerick', 'بيليريك', 'tank', 'التجوال', null, null, 70, null, null, null, null, null),
('gloo', 'غلو', 'tank', 'التجوال', null, null, 54, null, null, null, null, null),
('edith', 'إيديث', 'tank', 'التجوال', null, null, 59, null, null, null, null, null),
('gatotkaca', 'غاتوتكاكا', 'tank', 'خط الخبرة', null, null, 53, null, null, null, null, null),
('chip', 'تشيب', 'tank', 'التجوال', null, null, 55, null, null, null, null, null),
('rafaela', 'رافاييلا', 'sup', 'التجوال', null, null, 74, null, null, null, null, null),
('angela', 'أنجيلا', 'sup', 'التجوال', null, null, 78, null, null, null, null, null),
('diggie', 'ديغي', 'sup', 'التجوال', null, null, 79, null, null, null, null, null),
('carmilla', 'كارميلا', 'sup', 'التجوال', null, null, 53, null, null, null, null, null),
('mathilda', 'ماتيلدا', 'sup', 'التجوال', null, null, 81, null, null, null, null, null),
('floryn', 'فلورين', 'sup', 'التجوال', null, null, 63, null, null, null, null, null),
('faramis', 'فراميس', 'sup', 'التجوال', null, null, 54, null, null, null, null, null),
('kalea', 'كاليا', 'sup', 'التجوال', null, null, 57, null, null, null, null, null),
('natan', 'ناتان', 'mm', 'خط الذهب', 'B', null, 64, null, null, null, null, null),
('layla', 'ليلا', 'mm', 'خط الذهب', 'C', null, 93, null, null, null, null, null),
('karrie', 'كاري', 'mm', 'خط الذهب', 'A', null, 86, null, null, null, null, null);

-- ===== بيانات الكاونترات (مولَّدة تلقائياً) =====
insert into counters (subject, counter, score, delta, reason) values
('esmeralda', 'dyrroth', 94, 3.7, 'ضرره المئوي يخترق كل درع تبنيه'),
('esmeralda', 'natan', 89, 2.7, 'يستنزفها من مسافة لا تصلها'),
('esmeralda', 'karrie', 88, 2.7, 'ضررها الحقيقي يتجاهل الدرع كلياً'),
('esmeralda', 'atlas', 84, null, 'يسحبها بعيداً قبل أن تبني درعها'),
('esmeralda', 'baxia', 79, null, 'يقطع تعافيها بنسبة كبيرة'),
('esmeralda', 'hayabusa', 72, null, 'يصلها من الظل قبل اكتمال دورة درعها'),
('sora', 'melissa', 90, 2.9, 'تستنزفه من نطاق آمن قبل الاشتباك'),
('sora', 'phoveus', 88, 2.5, 'يعاقب كل اندفاعاته تلقائياً'),
('sora', 'khufra', 82, 2.1, 'يُلغي اندفاعه ويجمّده وسط فريقه'),
('phoveus', 'granger', 72, null, 'يستنزفه من مسافة بلا اقتراب'),
('phoveus', 'paquito', 70, null, 'لكماته السريعة تفوق بقاءه'),
('khufra', 'lunox', 68, null, 'تتجاوز كرته عبر أشكالها المزدوجة'),
('khufra', 'xavier', 65, null, 'يقصفه من مدى بعيد بلا اقتراب'),
('khufra', 'gusion', 63, null, 'انفجاره السريع يسبق رد فعله'),
('melissa', 'layla', 72, null, 'مدى مماثل يستنزفها مبكراً'),
('melissa', 'vale', 75, null, 'يقتحم مظلتها بمهارات لا تُمنع'),
('melissa', 'yin', 78, null, 'يلاحقها عبر التضاعف بلا مهرب'),
('melissa', 'hayabusa', 85, null, 'يصلها من الظل قبل تفعيل مظلتها'),
('hayabusa', 'chip', 77, null, 'يقاطع سلسلة ظلاله بالتحكّم المتكرر'),
('hayabusa', 'eudora', 73, null, 'صعقتها الفورية تُنهي كومبوه قبل أن يبدأ'),
('hayabusa', 'khufra', 80, null, 'يُلغي كل ظلاله وحركته الخاصة'),
('hayabusa', 'akai', 72, null, 'دورانه يقاطع كومبوه القصير'),
('hayabusa', 'atlas', 70, null, 'يسحبه من مسافة قبل أن يُنفّذ كومبوه'),
('hayabusa', 'barats', 68, null, 'تحكّمه الصلب يمنع كل الارتدادات'),
('fanny', 'khufra', 85, null, 'يقطع حبالها ويقفز إليها فوراً'),
('fanny', 'minsitthar', 80, null, 'يوقف الاندفاع ويقطع سلسلة الحبال'),
('fanny', 'phoveus', 85, null, 'كل حبل تستخدمه يغذّي ألته'),
('fanny', 'masha', 65, 3, 'ضغطها المستمر يفوق بقاء فاني'),
('fanny', 'lukas', 63, 2.7, 'يطاردها بنفس مستوى حركتها'),
('fanny', 'moskov', 60, 3, 'رمحه يخترقها من مسافة الأمان'),
('estes', 'baxia', 88, null, 'يقلّل كل علاجه بنسبة كبيرة'),
('estes', 'dyrroth', 65, null, 'ضرره المئوي يتجاوز فائدة العلاج'),
('estes', 'freya', 62, null, 'مبارزتها السريعة تسبق دورة العلاج'),
('zhuxin', 'khufra', 75, null, 'يمنع أي هروب بعد سلاسلها'),
('zhuxin', 'fanny', 70, null, 'تصلها بسرعة قبل إكمال السلسلة'),
('zhuxin', 'hayabusa', 68, null, 'يصلها من الظل بضرر انفجاري سريع'),
('zhuxin', 'lancelot', 66, null, 'يقتحمها قبل أن تُثبّت السلاسل'),
('dyrroth', 'baxia', 60, null, 'بقاؤه المرتفع يمتص انفجاره القصير'),
('dyrroth', 'terizla', 66, null, 'دفاعه المرتفع يستوعب انفجاره'),
('dyrroth', 'guinevere', 64, null, 'ترفعه في الهواء قبل أن يبدأ هجومه'),
('atlas', 'karrie', 68, null, 'ضررها الحقيقي يتجاهل دفاعه'),
('atlas', 'cecilion', 66, null, 'ضررها التراكمي يفوق بقاءه'),
('minsitthar', 'ling', 82, null, 'ألته تمنع كل حركاته الخاصة'),
('minsitthar', 'martis', 65, null, 'قفزته تصل قبل أن يُثبّت هدفه'),
('minsitthar', 'harith', 63, null, 'يقتحمه من بعيد بلا اعتماد على الاندفاع'),
('layla', 'ling', 85, null, 'يصلها من فوق الجدران بلا مهرب'),
('layla', 'hayabusa', 80, null, 'ظلاله تصلها من زوايا غير متوقعة'),
('layla', 'saber', 75, null, 'ألته الفورية تُنهيها قبل أي رد فعل'),
('layla', 'alucard', 70, null, 'يقفز إليها ويمتص دمها بسرعة'),
('karrie', 'minsitthar', 58, null, 'تحكّمه يقاطع دورة ضربها'),
('karrie', 'lolita', 60, null, 'درعها يمتص كل ضرباتها المتتالية'),
('karrie', 'moskov', 55, null, 'رمحه يستنزفها من مسافة أبعد'),
('tigreal', 'saber', 75, null, 'ألته الفورية تسبق أي تدخّل'),
('tigreal', 'eudora', 68, null, 'صعقتها تُبعده قبل أن يجمع فريقه'),
('akai', 'saber', 66, null, 'اغتيال سريع قبل أن يدور'),
('akai', 'moskov', 64, null, 'يستنزفه من مدى بعيد'),
('franco', 'tigreal', 67, null, 'يفتح الاشتباك قبل أن يخطّف'),
('franco', 'johnson', 65, null, 'يمتص خطّافه ويردّ الاشتباك'),
('franco', 'hanzo', 63, null, 'يهرب من الخطّاف عبر التحوّل للروح'),
('minotaur', 'freya', 66, null, 'مبارزة سريعة تفوق تعافيه'),
('minotaur', 'eudora', 62, null, 'صعقة فورية تمنع اندفاعه'),
('lolita', 'clint', 60, null, 'يستنزفها من خلف درعها'),
('lolita', 'akai', 58, null, 'تحكّم مستمر يتجاوز درعها'),
('johnson', 'eudora', 62, null, 'صعقتها تُسقطه فور نزوله من السيارة'),
('johnson', 'kagura', 60, null, 'مظلتها تصدّ سيارته وتضرّه'),
('gatotkaca', 'eudora', 63, null, 'صعقة فورية قبل أن يبدأ ألته'),
('gatotkaca', 'karrie', 61, null, 'ضررها الحقيقي يخترق درعه'),
('grock', 'terizla', 67, null, 'مطرقته تكسر جداره بضربة واحدة'),
('grock', 'franco', 60, null, 'يخطّفه قبل أن يستقر خلف جداره'),
('hylos', 'hayabusa', 63, null, 'يصله بسرعة قبل أن يمتص الضرر'),
('hylos', 'lancelot', 61, null, 'انفجار سريع يتجاوز دفاعه المتصاعد'),
('uranus', 'fanny', 70, null, 'حبالها لا تتأثر بتجدّده المستمر'),
('uranus', 'cyclops', 58, null, 'يجمّده قبل أن يبدأ تجدّده'),
('belerick', 'gusion', 62, null, 'انفجاره السريع يسبق رد الضرر'),
('belerick', 'lancelot', 60, null, 'يخترقه بسرعة قبل أن يردّ'),
('terizla', 'esmeralda', 68, 3.2, 'بقاؤها يستنزف مطرقته البطيئة'),
('terizla', 'guinevere', 63, null, 'ترفعه في الهواء وتُنهي هجومه'),
('baxia', 'gusion', 66, null, 'انفجار سريع قبل أن يقلّل العلاج'),
('baxia', 'harley', 60, null, 'يقتحمه بسرعة عبر التخفّي والظهور'),
('barats', 'atlas', 65, null, 'يسحبه بعيداً عن حجمه المتضخّم'),
('barats', 'cecilion', 60, null, 'ضرر تراكمي يتجاوز حجمه ببطء'),
('gloo', 'beatrix', 62, null, 'أسلحتها المتعددة تفكّك أشكاله'),
('gloo', 'brody', 58, null, 'ضربات متتالية تمنعه من الانقسام بأمان'),
('edith', 'natan', 60, null, 'ضرر مستمر من مسافة آمنة'),
('edith', 'aamon', 58, null, 'يخترق درعها الآلي بسرعة'),
('balmond', 'clint', 62, null, 'يستنزفه قبل أن يقترب'),
('balmond', 'alucard', 58, null, 'مبارزة سريعة تفوق ألته الإعدامية'),
('alucard', 'eudora', 65, null, 'صعقة فورية تقاطع اندفاعه'),
('alucard', 'saber', 60, null, 'ألته الفورية تُنهيه قبل أن يبدأ'),
('bane', 'chou', 60, null, 'ركلته تقاطع مهاراته المائية'),
('bane', 'bruno', 56, null, 'يستنزفه من الخط بضربات متتالية'),
('zilong', 'akai', 63, null, 'تحكّم مستمر يمنع دوراته السريعة'),
('zilong', 'gatotkaca', 58, null, 'دفاع مرتفع يستوعب هجماته'),
('freya', 'franco', 65, null, 'يخطّفها بعيداً عن أهدافها'),
('freya', 'chou', 60, null, 'ركلته تقاطع تبديل أسلحتها'),
('chou', 'bruno', 60, 2.3, 'مدى يستنزفه قبل ركلته الحاسمة'),
('chou', 'esmeralda', 82, null, 'تمتص ركلاته وتصمد في المبارزة'),
('sun', 'alucard', 60, null, 'مصّ دمه يتفوّق على نسخه المتعددة'),
('sun', 'miya', 56, null, 'ضرر مستمر يفكّك نسخه بسرعة'),
('alpha', 'clint', 58, null, 'يستنزفه قبل أن يُفعّل نسخته'),
('alpha', 'eudora', 56, null, 'صعقة فورية تقاطع اندفاعه'),
('ruby', 'freya', 60, null, 'مبارزة متكافئة تميل بخفة حركتها'),
('ruby', 'miya', 55, null, 'ضرر مستمر يتفوّق على تعافيها'),
('hilda', 'freya', 60, null, 'خفّة حركة تتفوّق في المبارزة الطويلة'),
('hilda', 'alucard', 58, null, 'مصّ دم أعلى يحسم المبارزة'),
('lapulapu', 'karrie', 62, null, 'ضرر حقيقي يخترق أشكاله المتعددة'),
('lapulapu', 'claude', 58, null, 'يستغل مرآته للضغط من بعيد'),
('argus', 'lancelot', 60, null, 'انفجار سريع قبل تفعيل خلوده'),
('argus', 'harley', 56, null, 'يقتحمه ويهرب بأمان من رد فعله'),
('jawhead', 'kagura', 60, null, 'مظلتها تصدّ قذفه وترتد عليه'),
('jawhead', 'pharsa', 56, null, 'تستنزفه من مدى بعيد'),
('martis', 'freya', 60, null, 'خفّة حركتها تفلت من قفزاته'),
('martis', 'akai', 57, null, 'تحكّم مستمر يمنع تصفير كولداونه'),
('kaja', 'helcurt', 62, null, 'يُعمي رؤيته قبل أن يُمسك هدفه'),
('kaja', 'grock', 58, null, 'جداره يمنع وصوله للهدف'),
('aldous', 'alice', 60, null, 'تمتص لكماته وتتغذّى على دمه'),
('aldous', 'zhask', 56, null, 'تستنزفه قبل أن يكدّس اللكمات'),
('leomord', 'lunox', 62, null, 'ضرر سحري متصاعد يتفوّق على حصانه'),
('leomord', 'selena', 58, null, 'اغتيال فوري قبل أن يستدعي حصانه'),
('thamuz', 'selena', 60, null, 'اغتيال سريع يقاطع دورة تجدّده'),
('thamuz', 'lunox', 58, null, 'ضرر سحري يتجاوز تعافيه ببطء'),
('badang', 'gusion', 60, null, 'انفجار سريع قبل أن يمسك بحبله'),
('badang', 'selena', 56, null, 'اغتيال فوري يسبق قبضته'),
('guinevere', 'selena', 60, null, 'اغتيال فوري قبل أن ترفع هدفها'),
('guinevere', 'claude', 56, null, 'مرآته تُبعد ضرر ألتها الجماعي'),
('xborg', 'lunox', 62, null, 'ضرر سحري متصاعد يخترق درعه المتجدّد'),
('xborg', 'akai', 56, null, 'تحكّم مستمر يمنع تفعيل درعه'),
('silvanna', 'wanwan', 58, null, 'حركة عالية تفلت من نطاق سيفها'),
('silvanna', 'xborg', 56, null, 'درعه يستوعب ضررها التراكمي'),
('yuzhong', 'karrie', 62, null, 'ضرر حقيقي يتجاوز شكله التنّيني'),
('yuzhong', 'helcurt', 56, null, 'يُعميه قبل أن يتحوّل لشكله الكامل'),
('khaleed', 'atlas', 60, null, 'يسحبه بعيداً عن مصادر مياهه'),
('khaleed', 'yuzhong', 56, null, 'يستنزفه بضرر مستمر متصاعد'),
('paquito', 'benedetta', 60, null, 'اندفاعها يفلت من نطاق لكماته'),
('paquito', 'ling', 56, null, 'حركته العمودية تتفادى ملاحقته'),
('aulus', 'phoveus', 65, null, 'يعاقب اندفاعاته المتكرّرة تلقائياً'),
('aulus', 'natan', 58, null, 'يستنزفه من مسافة قبل تصاعد سرعته'),
('yin', 'edith', 60, null, 'درعها يمتص انقضاضاته المتكررة'),
('yin', 'aamon', 56, null, 'اغتيال أسرع يسبق مضاعفة ضرره'),
('julian', 'aamon', 58, null, 'اغتيال فوري يقاطع تحوّله'),
('julian', 'edith', 56, null, 'درعها يستوعب ضربه المتتالي'),
('fredrinn', 'xborg', 60, null, 'درعه المتجدّد يقاوم تخزين ضرره'),
('fredrinn', 'karrie', 56, null, 'ضرر حقيقي يتجاوز تحوّله الدفاعي'),
('arlott', 'thamuz', 58, null, 'تجدّده يفوق ضرر اندفاعاته'),
('arlott', 'nana', 54, null, 'تحوّلها يُفلت هدفه من قبضته'),
('cici', 'ling', 58, null, 'حركة أعلى تفلت من رقصها'),
('cici', 'lancelot', 55, null, 'انفجار أسرع يسبق تدويرها'),
('saber', 'tigreal', 60, null, 'ألته الفورية تمنع دخول سيبر بأمان'),
('saber', 'fanny', 56, null, 'حركتها العالية تفلت من ألته المستقيمة'),
('karina', 'eudora', 60, null, 'صعقة فورية تقاطع تحويلها للسحر'),
('karina', 'ruby', 56, null, 'مبارزة طويلة تستنزف انفجارها القصير'),
('natalia', 'saber', 58, null, 'يكشفها ويقتلها رغم تخفّيها'),
('natalia', 'kagura', 54, null, 'مظلتها تصدّ اغتيالها المفاجئ'),
('lancelot', 'mathilda', 85, 3.5, 'تُبعده عن هدفه وتقاطع اندفاعاته'),
('lancelot', 'fanny', 60, null, 'حركة أعلى تفلته من سيوفه'),
('lancelot', 'grock', 56, null, 'جداره يقاطع مسار اندفاعه'),
('helcurt', 'roger', 60, null, 'شكله الذئبي يكشفه رغم العتمة'),
('helcurt', 'hayabusa', 56, null, 'ظلاله تفلت من نطاق تعميته'),
('selena', 'gusion', 58, null, 'انفجار أسرع يسبق سهمها من العتمة'),
('selena', 'helcurt', 55, null, 'يكشفها قبل أن تكمن للهجوم'),
('hanzo', 'leomord', 58, null, 'يضرب روحه الحقيقية رغم النسخ'),
('hanzo', 'selena', 55, null, 'سهم من العتمة يفاجئه قبل هجومه'),
('ling', 'valir', 60, null, 'دفعه المتكرر يفسد قفزاته'),
('ling', 'khufra', 58, null, 'كرته تُلغي كل قفزاته عبر الجدران'),
('benedetta', 'atlas', 60, null, 'يسحبها قبل أن تُكمل اندفاعاتها'),
('benedetta', 'barats', 56, null, 'تحكّمه الصلب يمنع اندفاعها الدرعي'),
('mathilda', 'luoyi', 58, null, 'بوابتها تُفلت الهدف من قبضتها'),
('mathilda', 'carmilla', 54, null, 'ربطها يقاطع نطها المتكرر'),
('aamon', 'natan', 58, null, 'يستنزفه من بعيد قبل اقترابه'),
('aamon', 'paquito', 55, null, 'لكمات سريعة تسبق تخفّيه بالشظايا'),
('joy', 'zilong', 56, null, 'دوراته السريعة تفلت من رقصها'),
('joy', 'hanabi', 54, null, 'ضرر مستمر يتجاوز درعها المرن'),
('nolan', 'martis', 60, null, 'قفزته تصل قبل أن يُخفي نسخته'),
('nolan', 'franco', 56, null, 'يخطّفه قبل أن يبدأ ظهوره المفاجئ'),
('nolan', 'khufra', 58, null, 'يُلغي اندفاعه ويجمّده وسط فريقه'),
('suyou', 'badang', 56, null, 'قبضته تقاطع اندماج سيفيه'),
('suyou', 'edith', 54, null, 'درعها يمتص ضربه السريع'),
('miya', 'natalia', 58, null, 'اغتيال صامت يسبق كل رد فعل'),
('miya', 'hayabusa', 56, null, 'يصلها من الظل بضرر انفجاري'),
('bruno', 'moskov', 56, null, 'مدى أبعد يستنزفه قبل اقترابه'),
('bruno', 'freya', 54, null, 'خفّة حركة تُفلتها من كرات برونو'),
('clint', 'eudora', 56, null, 'صعقة فورية تمنع دفعه الاستراتيجي'),
('clint', 'akai', 54, null, 'تحكّم مستمر يمنع مسافته الآمنة'),
('yisunshin', 'karina', 56, null, 'اغتيال سريع يسبق سحبه للأرواح'),
('yisunshin', 'eudora', 53, null, 'صعقة فورية تقاطع ألته المتنقلة'),
('moskov', 'karina', 56, null, 'اغتيال قصير المدى يتجاوز رمحه'),
('moskov', 'saber', 53, null, 'ألته الفورية تُنهيه قبل أي رد'),
('roger', 'alucard', 56, null, 'مصّ دم أعلى يحسم المبارزة'),
('roger', 'aurora', 53, null, 'تجميد مستمر يمنع تحوّله للذئب'),
('irithel', 'natalia', 58, null, 'اغتيال صامت يسبق أي رد فعل منها'),
('irithel', 'freya', 54, null, 'خفّة حركة تدخل نطاقها بأمان'),
('lesley', 'esmeralda', 60, null, 'تمتص طلقاتها وتصمد في المبارزة'),
('lesley', 'helcurt', 54, null, 'يُعميها قبل أن تتخفّى للتصويب'),
('hanabi', 'natalia', 56, null, 'اغتيال صامت يخترق درعها'),
('hanabi', 'fanny', 53, null, 'وصول سريع من فوق الجدران'),
('claude', 'lesley', 72, null, 'تقنصه من مدى أبعد من مرآته'),
('claude', 'bruno', 68, null, 'ضغط مستمر يقاطع تبديل مواقعه'),
('kimmy', 'gusion', 56, null, 'انفجار سريع قبل أن تبدّل أسلحتها'),
('kimmy', 'aldous', 53, null, 'يتراكم عليها بلا اعتماد على المدى'),
('granger', 'fanny', 70, 3.2, 'وصول سريع يقطع دورة رصاصاته الست'),
('granger', 'selena', 60, null, 'كمين مفاجئ يسبق استعداده'),
('wanwan', 'ling', 62, null, 'حركة عمودية تتفادى نطاق سيفها'),
('wanwan', 'esmeralda', 58, null, 'تمتص هجماتها المتتالية وتصمد'),
('popolandkupa', 'cecilion', 56, null, 'ضرر تراكمي يتفوّق على دعم الذئب'),
('popolandkupa', 'ling', 54, null, 'حركة عالية تتفادى هجمات الثنائي'),
('brody', 'ling', 56, null, 'حركة عمودية تتفادى ضرباته'),
('brody', 'yuzhong', 54, null, 'بقاء مرتفع يستوعب ضرباته المتتالية'),
('beatrix', 'benedetta', 56, null, 'اندفاعها يفلت من تبديل أسلحتها'),
('beatrix', 'paquito', 53, null, 'لكمات سريعة تقاطع تبديلها للسلاح'),
('natan', 'benedetta', 58, null, 'اندفاع سريع يخترق نسخته الوهمية'),
('natan', 'atlas', 54, null, 'يسحبه بعيداً عن مسافته الآمنة'),
('ixia', 'moskov', 56, null, 'مدى أبعد يستنزفها قبل اقترابها'),
('ixia', 'karrie', 53, null, 'ضرر حقيقي يتجاوز رذاذها الجماعي'),
('alice', 'chou', 58, null, 'ركلته تقاطع تغذيتها على الدم'),
('alice', 'hanabi', 54, null, 'ضرر مستمر يتفوّق على مصّها للدم'),
('nana', 'silvanna', 56, null, 'سيفها يلاحق قططها المتحوّلة'),
('nana', 'moskov', 53, null, 'مدى أبعد يستنزفها قبل اقترابها'),
('eudora', 'akai', 58, null, 'تحكّم مستمر يمنع صعقتها الفورية'),
('eudora', 'sun', 53, null, 'نسخه المتعددة تُشتّت صعقتها الوحيدة'),
('gord', 'tigreal', 58, null, 'ألته الفورية تقاطع ثباته'),
('gord', 'bruno', 53, null, 'حركة تتفادى قذائفه البطيئة'),
('kagura', 'karina', 56, null, 'اغتيال سريع قبل أن تفتح مظلتها'),
('kagura', 'zilong', 53, null, 'دورات سريعة تخترق مظلتها'),
('cyclops', 'zilong', 54, null, 'ضرر مستمر يتفوّق على تجميده'),
('cyclops', 'alucard', 52, null, 'مصّ دم يستوعب ضرره السحري'),
('aurora', 'fanny', 56, null, 'حركة عالية تتفادى تجميدها'),
('aurora', 'natalia', 53, null, 'اغتيال صامت يسبق تجميدها'),
('vexana', 'aurora', 54, null, 'تجميد مضاد يقاطع تعويذاتها'),
('vexana', 'karina', 52, null, 'اغتيال سريع قبل أن تستحضر الأرواح'),
('harley', 'jawhead', 56, null, 'قذفه يمنع دخوله وخروجه الآمن'),
('harley', 'hayabusa', 53, null, 'يصله بالظل قبل أن يهرب'),
('odette', 'guinevere', 56, null, 'ترفعها قبل أن تكمل ألتها الدائرية'),
('odette', 'chou', 53, null, 'ركلته تقاطع تجميعها للألت'),
('zhask', 'saber', 54, null, 'ألته الفورية تدمّر العشّ وتقتلها'),
('zhask', 'natalia', 52, null, 'اغتيال صامت يسبق استحضار العشّ'),
('pharsa', 'franco', 56, null, 'يخطّفها من مسافتها الآمنة'),
('pharsa', 'fanny', 53, null, 'وصول سريع عبر الحبال'),
('valir', 'lancelot', 54, null, 'انفجار سريع يقاطع دورة نيرانه'),
('valir', 'kaja', 52, null, 'يمسكها قبل أن تُشعل مساحتها'),
('change', 'saber', 54, null, 'ألته الفورية تُنهي جرّتها بسرعة'),
('change', 'chou', 52, null, 'ركلته تقاطع تدويرها لجرّاتها'),
('vale', 'chou', 56, null, 'ركلته تقاطع إعصارها التصاعدي'),
('vale', 'helcurt', 53, null, 'يُعميه قبل أن يجمع الأهداف'),
('lunox', 'valentina', 78, null, 'تسرق شكلها وتقلب المبارزة'),
('lunox', 'phoveus', 72, null, 'بقاؤه يستوعب انفجارها في الوضعين'),
('lunox', 'ruby', 68, null, 'مبارزة طويلة تستنزف تحوّلاتها'),
('harith', 'minsitthar', 60, null, 'ألته تُلغي اندفاعه بين الأبعاد'),
('harith', 'esmeralda', 56, null, 'تمتص ضرره وتصمد في وجهه'),
('kadita', 'helcurt', 56, null, 'يُعميها قبل أن تسحب هدفها'),
('kadita', 'natalia', 53, null, 'اغتيال صامت يسبق اختفاءها'),
('lylia', 'guinevere', 54, null, 'ترفعها قبل أن تُشعل قنابلها'),
('lylia', 'xborg', 52, null, 'درعه يستوعب انفجار قنابلها'),
('cecilion', 'lunox', 56, null, 'ضرر مستمر يتفوّق على تراكمه البطيء'),
('cecilion', 'chou', 53, null, 'ركلته تصله رغم تراكم دمه'),
('luoyi', 'natalia', 54, null, 'اغتيال صامت يقاطع تبديل أبعادها'),
('luoyi', 'hayabusa', 52, null, 'يصلها من الظل عبر أبعادها'),
('yve', 'helcurt', 54, null, 'يُعميها قبل أن تُنشئ نجومها'),
('yve', 'nana', 52, null, 'تحوّلها يُفلت الهدف من ألتها'),
('valentina', 'wanwan', 56, null, 'حركة عالية تفلت من سرقتها للمهارات'),
('valentina', 'alice', 53, null, 'تمتص ضررها وتتغذّى على دمها'),
('xavier', 'helcurt', 56, null, 'يُعميه قبل أن يقصف من بعيد'),
('xavier', 'fanny', 53, null, 'وصول سريع يخترق مداه الطويل'),
('novaria', 'lolita', 54, null, 'درعها يمتص قنصها من العتمة'),
('novaria', 'yuzhong', 52, null, 'بقاء مرتفع يستوعب ضربها الخفي'),
('zetian', 'valentina', 60, null, 'تسرق شكلها وتُفلت من منطقتها'),
('zetian', 'harith', 58, null, 'حركة عالية تتفادى مناطقها'),
('rafaela', 'karina', 58, null, 'اغتيال سريع يقاطع علاجها المستمر'),
('rafaela', 'saber', 54, null, 'ألته الفورية تُنهيها قبل الهروب'),
('diggie', 'aldous', 54, null, 'يتراكم عليها بلا اعتماد على التحكّم'),
('diggie', 'lancelot', 52, null, 'انفجار سريع يسبق بيضتها الواقية'),
('angela', 'lancelot', 56, null, 'انفجار سريع يقتل حاملها قبل الالتصاق'),
('angela', 'lesley', 52, null, 'تقنص حاملها من مسافة آمنة'),
('faramis', 'xborg', 54, null, 'درعه المتجدّد يقاوم إحياءها للفريق'),
('faramis', 'lylia', 52, null, 'قنابلها تمنع تجمّع الفريق للإحياء'),
('floryn', 'eudora', 54, null, 'صعقة فورية تقاطع علاجها عن بعد'),
('floryn', 'kagura', 52, null, 'مظلتها تصدّ علاجها المساحي'),
('chip', 'baxia', 54, null, 'يقلّل كل علاج بوابته الجماعية'),
('chip', 'wanwan', 52, null, 'حركة عالية تفلت من نقل بوابته');
